on:
  workflow_dispatch:
#  push:

name: build-wheels

permissions:
  contents: write

jobs:
  build-wheels:
    runs-on: ubuntu-24.04
    name: Build FlexiConc wheels

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Check out CLiC
        uses: actions/checkout@v4
      - name: Build wheels
        run: ./build.sh
      - name: Commit wheel changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automatically built wheels"
          git push
